volumes:
  quakedata:

services:
  db:
    image: mongo:4.2
    hostname: db
    volumes:
      - quakedata:/data/db
    ports:
        - "27017:27017"

  app:
    build: .
    hostname: app
    command: --dbconn=mongodb://db:27017
    ports:
      - "8080:8080"