name: build
on:
  push:
    branches:
      - main
    tags:
    paths:
      - ".github/workflows/ci-build.yml"
      - "app/**""
      - "Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/ci-build.yml"
      - "app/**""
      - "Dockerfile"

jobs:

  build-images:
    name: build docker images
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.49.0

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

    - name: build and push latest image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker build -t adobromilskiy/quake3-stats:latest .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-stats:latest

    - name: build and push tagged image
      if: github.event_name == 'push' && github.event.ref_type == 'tag'
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        docker build -t adobromilskiy/quake3-stats:${GIT_TAG} .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-stats:${GIT_TAG}
        docker tag adobromilskiy/quake3-stats:${GIT_TAG} adobromilskiy/quake3-stats:latest
        docker push adobromilskiy/quake3-stats:latest